import { cookieStorage, createStorage } from "wagmi"
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi"
import type { Chain } from "viem"

// Define Viction Mainnet as a custom chain
export const victionMainnet = {
  id: 88,
  name: "Viction Mainnet",
  nativeCurrency: {
    decimals: 18,
    name: "VIC",
    symbol: "VIC",
  },
  rpcUrls: {
    default: { http: ["https://rpc.viction.xyz/"] },
    public: { http: ["https://rpc.viction.xyz/"] },
  },
  blockExplorers: {
    default: { name: "VicScan", url: "https://www.vicscan.xyz/" },
  },
} as const satisfies Chain

// Read Project ID from environment variables
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error("NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local")
}

// Define supported networks (must be non-empty array)
export const networks: [Chain, ...Chain[]] = [victionMainnet]

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: true,
  projectId,
  networks,
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig
