import { cookieStorage, createStorage } from "wagmi"
import { WagmiAdapter } from "@reown/appkit-adapter-wagmi"
import type { Chain } from "viem"

// Viction Mainnet configuration
export const victionMainnet: Chain = {
  id: 88,
  name: "Viction Mainnet",
  nativeCurrency: {
    decimals: 18,
    name: "VIC",
    symbol: "VIC",
  },
  rpcUrls: {
    default: {
      http: ["https://rpc.viction.xyz/"],
    },
    public: {
      http: ["https://rpc.viction.xyz/"],
    },
  },
  blockExplorers: {
    default: {
      name: "Vicscan",
      url: "https://www.vicscan.xyz/",
    },
  },
}

// Read Project ID from environment variables
export const projectId = process.env.NEXT_PUBLIC_PROJECT_ID

// Ensure Project ID is defined at build time
if (!projectId) {
  throw new Error("NEXT_PUBLIC_PROJECT_ID is not defined. Please set it in .env.local")
}

// Define supported networks
export const networks: [Chain, ...Chain[]] = [victionMainnet]

// Create the Wagmi adapter instance
export const wagmiAdapter = new WagmiAdapter({
  storage: createStorage({ storage: cookieStorage }),
  ssr: true,
  projectId,
  networks,
})

// Export the Wagmi config generated by the adapter
export const config = wagmiAdapter.wagmiConfig
